from __future__ import annotations

import logging

LOGGER = logging.getLogger("csdr_server")

EXIT_OUT_OF_BAND = 1
EXIT_BAD_SAMPLE_RATE = 2
EXIT_REQUEST_ERROR = 3

PR_SET_NAME = 15

DEFAULT_MODE = "iq"
VALID_MODES = {DEFAULT_MODE, "audio"}
DEFAULT_MODULATION = "am"
VALID_AUDIO_MODULATIONS = {DEFAULT_MODULATION, "lsb", "nfm", "usb", "wfm", "wfm_stereo"}
DEFAULT_SAMPLE_FORMAT = "f32"
VALID_SAMPLE_FORMATS = {DEFAULT_SAMPLE_FORMAT, "s16"}
DEFAULT_STREAM_OUTPUT_READ_SIZE = 65_536
DEFAULT_AUDIO_OUTPUT_FORMAT = "s16"
AM_AUDIO_OUTPUT_RATE = 16_000
AM_AUDIO_TRANSITION_BANDWIDTH = 0.005
AM_AUDIO_AGC_REFERENCE = 0.2
NFM_AUDIO_DEEMPHASIS_TAU = 300
WFM_IQ_RATE = 240_000
WFM_AUDIO_OUTPUT_RATE = 32_000
WFM_AUDIO_TRANSITION_BANDWIDTH = 0.05
WFM_DEEMPHASIS_REGION = "us"
SQUELCH_MIN_LEVEL = 0
SQUELCH_MAX_LEVEL = 100
SQUELCH_HYSTERESIS = 3.0
SQUELCH_HANG_SECONDS = 0.25
